### ISSUE TITLE
Composer install fail with RC5

### ISSUE THREAD

**Issue by eric-alpha7** [maestrano/maestrano-php#31]
Hi,

when using the composer configuration provided in documentation I have the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package maestrano/maestrano-php 1.0.0-RC5 exists as maestrano/maestrano-php[0.10.0, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.11.4, 0.11.5, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.5.1, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.9.2, 1.0.0-RC1, dev-master] but these are rejected by your constraint.
```

I don't see any RC5 in the list of package available, was it a mistype in the readme? RC1 is working fine.

**Comment by eric-alpha7** [comment]
@alexnoox  Just checked in the commit and saw you are the one who put RC5. thought you could be interested. ;)

**Comment by alexnoox** [comment]
Hi Eric,

Thank you for your feedback. It is effectively a typo ;)

Cheers
Alex
